import io
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

class PDFService:
    @staticmethod
    def generate_interview_pdf(interview_set: dict) -> bytes:
        """
        Generate a professional PDF of the interview questions, answers, and hints.
        Returns bytes of the PDF.
        """
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=54,
            bottomMargin=54
        )
        
        styles = getSampleStyleSheet()
        
        # Custom styles for a premium look
        title_style = ParagraphStyle(
            name='TitleStyle',
            fontName='Helvetica-Bold',
            fontSize=24,
            leading=28,
            textColor=colors.HexColor('#4F46E5'), # Indigo-600
            spaceAfter=6
        )
        
        subtitle_style = ParagraphStyle(
            name='SubtitleStyle',
            fontName='Helvetica',
            fontSize=12,
            leading=16,
            textColor=colors.HexColor('#4B5563'), # Gray-600
            spaceAfter=20
        )
        
        h2_style = ParagraphStyle(
            name='Heading2Style',
            fontName='Helvetica-Bold',
            fontSize=16,
            leading=20,
            textColor=colors.HexColor('#111827'), # Gray-900
            spaceBefore=15,
            spaceAfter=10,
            keepWithNext=True
        )
        
        meta_label_style = ParagraphStyle(
            name='MetaLabel',
            fontName='Helvetica-Bold',
            fontSize=10,
            leading=12,
            textColor=colors.HexColor('#374151')
        )
        
        meta_val_style = ParagraphStyle(
            name='MetaValue',
            fontName='Helvetica',
            fontSize=10,
            leading=12,
            textColor=colors.HexColor('#6B7280')
        )

        q_num_style = ParagraphStyle(
            name='QuestionNumber',
            fontName='Helvetica-Bold',
            fontSize=12,
            leading=15,
            textColor=colors.HexColor('#4F46E5')
        )

        q_text_style = ParagraphStyle(
            name='QuestionText',
            fontName='Helvetica-Bold',
            fontSize=12,
            leading=16,
            textColor=colors.HexColor('#1F2937')
        )
        
        label_style = ParagraphStyle(
            name='LabelStyle',
            fontName='Helvetica-Bold',
            fontSize=10,
            leading=12,
            textColor=colors.HexColor('#374151')
        )
        
        content_style = ParagraphStyle(
            name='ContentStyle',
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#4B5563')
        )
        
        hint_style = ParagraphStyle(
            name='HintStyle',
            fontName='Helvetica-Oblique',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#059669') # Green-600
        )
        
        story = []
        
        # Title
        story.append(Paragraph("AI Interview Question Set", title_style))
        story.append(Paragraph("Generated by AI Interview Question Generator", subtitle_style))
        story.append(Spacer(1, 10))
        
        # Metadata Table
        meta_data = [
            [
                Paragraph("Job Role:", meta_label_style), Paragraph(interview_set.get("role", "N/A"), meta_val_style),
                Paragraph("Experience:", meta_label_style), Paragraph(interview_set.get("experience_level", "Mid-Level"), meta_val_style)
            ],
            [
                Paragraph("Skill / Tech:", meta_label_style), Paragraph(interview_set.get("skill", "N/A"), meta_val_style),
                Paragraph("Difficulty:", meta_label_style), Paragraph(interview_set.get("difficulty", "N/A"), meta_val_style)
            ],
            [
                Paragraph("Question Type:", meta_label_style), Paragraph(interview_set.get("question_type", "N/A"), meta_val_style),
                Paragraph("Generated:", meta_label_style), Paragraph(interview_set.get("created_at")[:10] if interview_set.get("created_at") else "N/A", meta_val_style)
            ]
        ]
        
        meta_table = Table(meta_data, colWidths=[1.2*inch, 2.3*inch, 1.2*inch, 2.3*inch])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F9FAFB')),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('PADDING', (0,0), (-1,-1), 8),
            ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor('#E5E7EB')),
            ('INNERGRID', (0,0), (-1,-1), 0.25, colors.HexColor('#F3F4F6')),
        ]))
        
        story.append(meta_table)
        story.append(Spacer(1, 25))
        
        # Section Header
        story.append(Paragraph("Questions, Hints, and Model Answers", h2_style))
        story.append(Spacer(1, 10))
        
        # Questions list
        questions = interview_set.get("questions", [])
        for idx, q in enumerate(questions, 1):
            # Header line: Q1. Question Text
            q_header_data = [
                [Paragraph(f"Q{idx}.", q_num_style), Paragraph(q.get("question", ""), q_text_style)]
            ]
            q_header_table = Table(q_header_data, colWidths=[0.4*inch, 6.6*inch])
            q_header_table.setStyle(TableStyle([
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
                ('PADDING', (0,0), (-1,-1), 2),
            ]))
            story.append(q_header_table)
            
            # Difficulty tag
            story.append(Spacer(1, 4))
            diff_text = f"Difficulty: {q.get('difficulty', interview_set.get('difficulty', 'Medium'))}"
            story.append(Paragraph(f"<b>{diff_text}</b>", ParagraphStyle(
                name=f'diff_{idx}',
                fontName='Helvetica-Bold',
                fontSize=9,
                textColor=colors.HexColor('#6B7280'),
                leftIndent=30
            )))
            story.append(Spacer(1, 8))
            
            # Content table for Hint and Answer
            q_content_data = [
                [Paragraph("Hint:", label_style), Paragraph(q.get("hint", ""), hint_style)],
                [Paragraph("Model Answer:", label_style), Paragraph(q.get("answer", ""), content_style)]
            ]
            
            q_content_table = Table(q_content_data, colWidths=[1.1*inch, 5.5*inch])
            q_content_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#FFFFFF')),
                ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
                ('PADDING', (0,0), (-1,-1), 6),
                ('LINEBELOW', (0,0), (-1,-2), 0.5, colors.HexColor('#F3F4F6')),
                ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor('#F3F4F6')),
            ]))
            
            # Indent the content table to align with the question text
            q_content_container = Table([[Spacer(1, 1), q_content_table]], colWidths=[0.3*inch, 6.7*inch])
            q_content_container.setStyle(TableStyle([
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
                ('LEFTPADDING', (1,0), (1,0), 0),
                ('PADDING', (0,0), (-1,-1), 0),
            ]))
            
            story.append(q_content_container)
            story.append(Spacer(1, 15))
            
        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()
