import { jsPDF } from 'jspdf';

/**
 * Generate a beautifully formatted PDF client-side using jsPDF.
 */
export const exportToPdfClient = (interviewSet) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'letter'
  });

  const margins = {
    top: 54,
    bottom: 54,
    left: 54,
    right: 54
  };

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const printableWidth = pageWidth - margins.left - margins.right;

  let y = margins.top;

  // Helper to add text with wrapping and auto page breaks
  const addWrappedText = (text, x, fontSize, fontStyle = 'normal', color = '#374151', leading = 16) => {
    doc.setFont('helvetica', fontStyle);
    doc.setFontSize(fontSize);
    
    // Set color
    if (color.startsWith('#')) {
      const r = parseInt(color.slice(1, 3), 16);
      const g = parseInt(color.slice(3, 5), 16);
      const b = parseInt(color.slice(5, 7), 16);
      doc.setTextColor(r, g, b);
    }

    const lines = doc.splitTextToSize(text, printableWidth);
    
    lines.forEach((line) => {
      if (y + leading > pageHeight - margins.bottom) {
        doc.addPage();
        y = margins.top;
      }
      doc.text(line, x, y);
      y += leading;
    });
  };

  // Header Title
  addWrappedText('AI Interview Question Set', margins.left, 22, 'bold', '#4F46E5', 28);
  addWrappedText('Generated by InterviewAI Question Engine', margins.left, 10, 'normal', '#6B7280', 14);
  y += 10;

  // Metadata Panel
  doc.setFillColor(249, 250, 251); // Gray-50
  doc.setDrawColor(229, 231, 235); // Gray-200
  doc.roundedRect(margins.left, y, printableWidth, 75, 6, 6, 'FD');
  
  const metaYStart = y + 18;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(55, 65, 81); // Gray-700
  
  doc.text('Job Role:', margins.left + 15, metaYStart);
  doc.text('Core Skill:', margins.left + 15, metaYStart + 18);
  doc.text('Difficulty:', margins.left + 15, metaYStart + 36);

  doc.text('Experience:', margins.left + 220, metaYStart);
  doc.text('Type:', margins.left + 220, metaYStart + 18);
  doc.text('Date:', margins.left + 220, metaYStart + 36);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(107, 114, 128); // Gray-500
  doc.text(interviewSet.role || 'N/A', margins.left + 75, metaYStart);
  doc.text(interviewSet.skill || 'N/A', margins.left + 75, metaYStart + 18);
  doc.text(interviewSet.difficulty || 'N/A', margins.left + 75, metaYStart + 36);

  doc.text(interviewSet.experience_level || 'Mid-Level', margins.left + 290, metaYStart);
  doc.text(interviewSet.question_type || 'N/A', margins.left + 290, metaYStart + 18);
  doc.text((interviewSet.created_at || '').slice(0, 10), margins.left + 290, metaYStart + 36);

  y += 95;

  // Title
  addWrappedText('Questions, Hints, and Answers', margins.left, 14, 'bold', '#111827', 22);
  y += 10;

  // Loop questions
  const questions = interviewSet.questions || [];
  questions.forEach((q, idx) => {
    // Check page space for header
    if (y + 40 > pageHeight - margins.bottom) {
      doc.addPage();
      y = margins.top;
    }

    // Question Number and Text
    const qNum = `Q${idx + 1}. `;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(79, 70, 229); // Indigo-600
    doc.text(qNum, margins.left, y);

    const qTextX = margins.left + 22;
    addWrappedText(q.question, qTextX, 11, 'bold', '#1F2937', 16);
    y += 4;

    // Difficulty tag
    addWrappedText(`Difficulty: ${q.difficulty}`, qTextX, 8, 'bold', '#9CA3AF', 12);
    y += 6;

    // Hint
    addWrappedText('Hint:', qTextX, 9, 'bold', '#059669', 14);
    y -= 14; // adjust y since addWrappedText advanced it
    addWrappedText(q.hint, qTextX + 40, 9, 'italic', '#059669', 14);
    y += 4;

    // Answer
    addWrappedText('Answer:', qTextX, 9, 'bold', '#374151', 14);
    y -= 14;
    addWrappedText(q.answer, qTextX + 48, 9, 'normal', '#4B5563', 14);
    y += 16; // Add spacer between questions
  });

  // Save PDF
  const filename = `interview_${interviewSet.role || 'questions'}_${interviewSet.skill || ''}.pdf`
    .replace(/\s+/g, '_')
    .toLowerCase();
  doc.save(filename);
};
